### ISSUE TITLE
Is it possible to add packages via composer?

### ISSUE THREAD

**Issue by 11mb** [venyii/hipchat-commander#5]
Hi, 

Thanks for this awesome package. Very high code quality!
Is it possible (yet) to create a package that can be required via composer.json?

I would like to create package(s) to use the Jenkins and Jelastic API's. 

Maybe with a composer hook to call an install script in the package that will copy itself to the pkg directory?

**Comment by vntw** [comment]
Hi, sorry for the very long long delay. I haven't been using this project for quite some time because I left the job that used HipChat.

The plan was to support Composer packages, but I had problems with an integration unit-test ability in custom packages and planned to do it soon™, which of course never happened.

So right now, you're better off checking out/forking the repo and building your packages directly in the `pkg` directory.

Sorry!
